name: Builder

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      version:
        required: true
        type: string
      architecture:
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download ${{ inputs.project }}
        id: download
        run: |
          ./${{ inputs.project }}/fetch.sh \
            --version "${{ inputs.version }}"
      - name: Build ${{ inputs.project }}
        id: build
        run: |
          ./${{ inputs.project }}/build.sh \
            --version "${{ inputs.version }}" \
            --architecture "${{ inputs.architecture }}" \
            --static
      - name: Pack ${{ inputs.project }}
        id: pack
        run: |
          printf "TARBALL=%s\n" \
            "$(./${{ inputs.project }}/pack.sh \
                --version "${{ inputs.version }}" \
                --architecture "${{ inputs.architecture }}")" >> "$GITHUB_OUTPUT"
      - name: Upload ${{ inputs.project }}
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.project }}${{ inputs.version }}-${{ inputs.architecture }}
          path: ${{ steps.pack.outputs.TARBALL }}
          retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete old release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: ${{ inputs.project }}
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Collect tarballs
        run: |
          find . -name "${{ inputs.project }}${{ inputs.version }}*.tar.gz" -exec mv \{\} . \;
      - name: Generate README
        id: readme
        run: |
          VERSION="${{ inputs.version }}"; export VERSION
          envsubst < ./${{ inputs.project }}/RELEASE.md > /tmp/README.md
      - name: Create release
        id: release
        if: github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.gz"
          allowUpdates: true
          bodyFile: /tmp/README.md
          commit: ${{ github.ref }}
          name: ${{ inputs.project }} ${{ inputs.version }}
          tag: ${{ inputs.project }}${{ inputs.version}}
          replacesArtifacts: true
