name: jpeg

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "feature/*"
    paths:
      - "jpeg/**"
      - ".github/workflows/jpeg.yml"
      - ".github/workflows/_*.yml"

jobs:
  build:
    strategy:
      matrix:
        architecture:
          - linux-x86_64
          - linux-i386
        version:
          - "6b"
          - "7"
          - "8d"
          - "9e"
    uses: ./.github/workflows/_build.yml
    with:
      project: jpeg
      version: ${{ matrix.version }}
      architecture: ${{ matrix.architecture }}
      build-args: --host

  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        # Same list as above, no support for YAML anchors in workflows at the
        # moment.
        version:
          - "6b"
          - "7"
          - "8d"
          - "9e"
    uses: ./.github/workflows/_release.yml
    with:
      project: jpeg
      version: ${{ matrix.version }}
