name: tcl

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
    paths:
      - "tcl/**"
      - ".github/workflows/tcl.yml"

jobs:
  build:
    strategy:
      matrix:
        architecture:
          - linux-x86_64
          - linux-i386
        # These are the latest of the major versions according to
        # https://www.tcl.tk/software/tcltk/choose.html
        version:
          - "8.0.5"
          - "8.1.1"
          - "8.2.3"
          - "8.3.5"
          - "8.4.20"
        exclude:
          # Fails to build on i386 when linking statically
          - architecture: linux-i386
            version: "8.3.5"
    uses: ./.github/workflows/_build_n_release.yml
    with:
      project: tcl
      version: ${{ matrix.version }}
      architecture: ${{ matrix.architecture }}
