name: tk

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
    paths:
      - "tcl/**"
      - "tk/**"
      - ".github/workflows/tk.yml"
      - ".github/workflows/_*.yml"

jobs:
  build:
    strategy:
      matrix:
        architecture:
          - x86_64-unknown-linux-glibc
          - i386-unknown-linux-glibc
        # These are the latest of the major versions according to
        # https://www.tcl.tk/software/tcltk/choose.html
        version:
          - "8.0.5"
          - "8.1.1"
          - "8.2.3"
          - "8.3.5"
          - "8.4.20"
        exclude:
          # Fails to build on i386 when linking statically
          - architecture: i386-unknown-linux-glibc
            version: "8.3.5"
    uses: ./.github/workflows/_build.yml
    with:
      project: tk
      version: ${{ matrix.version }}
      architecture: ${{ matrix.architecture }}
      build-args: --static

  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        # Same list as above, no support for YAML anchors in workflows at the
        # moment.
        version:
          - "8.0.5"
          - "8.1.1"
          - "8.2.3"
          - "8.3.5"
          - "8.4.20"
    uses: ./.github/workflows/_release.yml
    with:
      project: tk
      version: ${{ matrix.version }}
