name: zlib

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
      - fix/*
    paths:
      - "zlib/**"
      - ".github/workflows/zlib.yml"
      - ".github/workflows/_*.yml"

jobs:
  build:
    strategy:
      matrix:
        architecture:
          - x86_64-unknown-linux-glibc
          - i386-unknown-linux-glibc
        # These are the latest of the major versions
        version:
          - "1.0.9"
          - "1.1.4"
          - "1.2.13"
    uses: ./.github/workflows/_build.yml
    with:
      project: zlib
      version: ${{ matrix.version }}
      architecture: ${{ matrix.architecture }}
      build-args: --host

  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        # Same list as above, no support for YAML anchors in workflows at the
        # moment.
        version:
          - "1.0.9"
          - "1.1.4"
          - "1.2.13"
    uses: ./.github/workflows/_release.yml
    with:
      project: zlib
      version: ${{ matrix.version }}
